### ISSUE TITLE
What's the default password?

### ISSUE THREAD

**Issue by ossplus** [getherbie/plugin-adminpanel#1]
in blueprint.yml the password is "88cceeb3a39d7f9172c228028e46cb69",
then ,what's the exact password? 
Another, can you offer a full english version herbie cms?there are many strings are not english.
thanks.

**Comment by tbreuss** [comment]
The Password is md5 encoded. Please set a new one using one of the available md5 online encoders like http://www.md5.cz

I'm aware of the missing translations and I'm going to work on this. I'll keep you informed.

**Comment by ossplus** [comment]
I know to use md5 encode tool.
But, for my paas demo platform, i cann't access the filesystem, i can't change the code. So i suggest you just change the md5 code to "getherbie.org" or "adminpanel". thanks.

Another issue, when i use herbie and set apache's documentroot to "web"dir, then the url for "@asset" is wrong. 
the asset url will be "//assets/default/css/styles.css" ;
it should be "/assets/default/css/styles.css"

**Comment by tbreuss** [comment]
The 2nd issue is fixed now.

**Comment by tbreuss** [comment]
Here is my (late) answer to your suggestion to set a default password like "getherbie.org" or similar. I think that this is not a good idea because someone would surely forget to reset a new password.
