### ISSUE TITLE
In welche Datei muss man die Konfigurations-Einstellungen einfügen

### ISSUE THREAD

**Issue by ghost** [getherbie/plugin-adminpanel#2]
Hallo Entwickler,
ich habe gesehen, dass Herbie ein Schweizer CMS ist und daher versuche ich es mal mit einem deutschen Issue.

Also mir ist nicht klar, in welche Datei auf dem Webspace ich diese Konfigurationseinstellungen dieses Plugins einfügen muss.

Ich habe das Plugin installiert, aktiviert und nun kann ich unter /adminpanel es aufrufen. Aber die Einstellungen und das Passwort sind noch nicht gesetzt und ich habe es nicht verstanden, in welche Datei man die Konfiguration des Plugins einfügen muss. 

Das MD5-Passwort kann ich schon noch erstellen, aber wo muss man es alles einfügen. Ich habe jetzt auf dem Webspace das Verzeichnis **/start-website/site/config** mit **/main.yml**.

Diese Datei ist es nicht oder??

Freue mich über eure baldige Hilfestellung. Vielen Dank!

**Comment by tbreuss** [comment]
Hallo Alex, sorry für die späte Antwort. Github hat mir kein Mail gesendet, oder es ist im Spam gelandet.

Du müsstest das PW in der main.yml Datei ablegen.
    plugins:
        config:
            adminpanel:
                password: "md5encoded"

Das Adminpanel ist allerdings noch "unfertig". Es kann noch nicht soooooo viel.

LG, Thomas

**Comment by tbreuss** [comment]
Du kannst es aber auch so machen wie hier:
https://github.com/getherbie/website/tree/master/site/config

Siehe Datei plugins/adminpanel.yml

**Comment by ghost** [comment]
Hallo Thomas, 
kein Problem und bist du noch hier heute? Irgendwie kann ich mich unter /adminpanel nicht einloggen. Ich habe das MD-Passwort im Internet erstellt und habe es in der Datei main.yml aber dort ohne Anführungszeichen eingefügt.

Doch im Frontend kein Login möglich. Übersehe ich noch etwas?

**Comment by tbreuss** [comment]
Hallo Alexander

Ich habe nun eine jungfräuliche Installation vorgenommen und anschliessend Adminpanel hinzugefügt. Der Login geht. Wie aber schon gesagt: Das Adminpanel ist „Work in progress“.

Unten habe ich meine Settings eingefügt. Ich kann Dir sonst alternativ auch meine komplette Herbie-Website (also www.getherbie.org) zum Spielen mailen. 

Liebe Grüsse,
Thomas

---

## COMPOSER.JSON

{
    "name": "getherbie/start-website",
    "homepage": "http://www.getherbie.org",
    "description": "The website starter",
    "type": "project",
    "minimum-stability": "dev",
    "license":"BSD-3-Clause",
    "require": {
        "php": ">=5.4.0",
        "getherbie/herbie": "dev-master",
        "getherbie/composer": "dev-master",
        "getherbie/plugin-simplecontact": "dev-master",
        "getherbie/plugin-simplesearch": "dev-master",
        "getherbie/plugin-adminpanel": "dev-master"  
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "Herbie\Composer\Installer::setPermission"
        ]
    },
    "extra": {
        "writable": [
            "site/cache/data",
            "site/cache/page",
            "site/cache/twig"
        ],
        "executable": []
    }
}

---

## CONFIG/MAIN.YML

nice_urls: true

plugins:
    enable:
        - simplecontact
        - simplesearch
        - adminpanel
    config:
        adminpanel:
            password: 098f6bcd4621d373cade4e832627b4f6

**Comment by tbreuss** [comment]
Das Passwort wäre in diesem Fall "test".

**Comment by ghost** [comment]
Hallo Thomas,
irgendwas scheint bei mir noch nicht zu stimmen. Gerne kannst du mir deine Webseite zum Spielen mailen. Das Blog ist auch schon erstellt und ich schaue es mir in jedem Falle an. 

Meine Mail: **power_sash@gmx.net**

Ich möchte einfach wissen, wie bei dir die sonstigen Einstellungen sind und warum es bei mir nicht klappen will. 

Also dann warte ich kurz auf deine Mail und freue mich im Vorfeld, dass ich mal ein bisschen in die Herbie-Welten eintauchen kann :smile:

**Comment by tbreuss** [comment]
Hab Dir die Website als ZIP gemailt.

**Comment by ghost** [comment]
Vielen Dank, Thomas.

Leider besteht weiterhin das Problem, dass ich mich unter /adminpanel nicht einloggen kann.

In der Datei main.yml sieht es bei mir zuunterst so aus:

config:
        simplesearch:
            use_page_cache: true
        disqus:
            twig: true
        highlightjs:
            style: zenburn
        adminpanel:
            password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Woran kann es liegen? Ich weiss es gerade nicht.

**Comment by tbreuss** [comment]
Den Login siehst du aber? Was hast du für eine Umgebung, Server, PHP, Browser etc.?

Von meinem iPod gesendet

**Comment by ghost** [comment]
Ja, den Login kann ich sehen.

Ich habe einen Managed Server bei All-inkl und eben auch PHP 5.5 bis 5.6, letzte mySQL-Version und nutze den Browse Firefox. Ich kann es nochmals mit Google Chrome probieren, falls sich da was tun wird. 

Aber schon seltsam, warum diese einfache Sache des Einloggens nicht klappen will.

**Comment by tbreuss** [comment]
Könnte etwas mit der Session zu tun haben. Das Adminpanel ist halt noch ziemlich unfertig und ungetestet.

Von meinem iPod gesendet

**Comment by ghost** [comment]
OK, dann muss ich erstmals abwarten, bis es fertig ist. Eine Möglichkeit, Inhalte im Frontend zu bearbeiten, habe ich aber nicht oder doch schon??

**Comment by ghost** [comment]
Ich weiss es nun, dass ich auch offline bloggen kann. Den Markdown-Editor habe ich installiert und brauche dann nur die .md-Files hochzuladen. Das sollte gehen.

**Comment by ghost** [comment]
Genial, ich habe den Fehler gefunden :smile: 

Also ich habe die Datei adminpanel.yml geöffnet und dort das Passwort(md5) geändert. Danach konnte ich mich im Admin unter /adminpanel auch schon einloggen. Super, alles geklappt.

Jetzt schaue ich es mir alles nochmals an!!

**Comment by ghost** [comment]
Oh man, Gott sei Dank, habe ich nichts gelöscht, denn ich habe eine GitHub-Verbindung zwischen meinen neuen Posts entdeckt. Das siehst du hier: http://wpzweinull.ch/cms/herbie/web/blog/2016/02/06-herbie-webseite-installiert-und-am-testen

Kann man das abstellen? Ich dachte ich habe schon was im GitHub-Repo dadurch löschen können :(

**Comment by tbreuss** [comment]
Super, dass das Problem gelöst ist. Wegen dem "neuen" Problem weiss ich leider nicht, was du meinst.

**Comment by ghost** [comment]
Also in den Blogposts von mir und bei euch im offiziellen Blog gibt es oben rechts ein GitHub-Icon und es wird ein Link zu eurem GitHub Repo generiert. Der Link ist aber dann nicht existent. Kann ich es irgendwie bei mir deaktivieren. Ich habe schon das Plugin Gist entfernt, da ich dachte, dass es das macht.

Und noch ein paar Fragen:
1. Erlaubt/st ihr/du mir, die Seite Dokumentation und Downloads in meinem Blog zu belassen? Es geht alles dort zu GitHub wie du weisst und das würde helfen, dieses CMS noch mehr unters Volk zu bringen. 

Ansonsten habe ich erstmals keine anderen Fragen und muss noch das System gut erkunden.

**Comment by tbreuss** [comment]
Um das Github-Icon zu entfernen, lösche die Zeichenfolge "{{ githublink() }}" in den folgenden Dateien:
- site/layouts/default/default.html
- site/layouts/default/blog.html
- site/layouts/default/documentation.html

Du kannst mit den Seiten Dokumentation & Downloads machen was du willst. Google-technisch könnte es allerdings für dich suboptimal sein (Stichwort: Duplicated Content).

**Comment by ghost** [comment]
Vielen Dank für die Hinweise und die Tipps, eben alles umgesetzt und die Doku habe ich auch gelöscht. Downloads lasse ich drin.

Du hast Recht, DC muss nicht sein und da ist Google doch sehr allergisch dagegen. 

Also nun habe ich erstmals einen Herbie Blog und kann mich frei entfalten und nach und nach alles verbloggen.
